CREATE TABLE PII_CATEGORY (
	ID INTEGER AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(1023),
	PRIMARY KEY (ID)
);

CREATE TABLE RECEIPT (
	CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
	VERSION VARCHAR(255) NOT NULL,
	JURISDICTION VARCHAR(255) NOT NULL,
	CONSENT_TIMESTAMP TIMESTAMP NOT NULL,
	COLLECTION_METHOD VARCHAR(255) NOT NULL,
	LANGUAGE VARCHAR(255) NOT NULL,
	PII_PRINCIPAL_ID VARCHAR(255) NOT NULL,
	PRINCIPAL_TENANT_DOMAIN VARCHAR(255),
	IS_SENSITIVE INTEGER NOT NULL,
	POLICY_URL VARCHAR(255) NOT NULL,
	PRIMARY KEY (CONSENT_RECEIPT_ID)
);

CREATE TABLE PURPOSE (
	ID INTEGER AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(1023),
	PRIMARY KEY (ID)
);

CREATE TABLE PURPOSE_CATEGORY (
	ID INTEGER AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(1023),
	PRIMARY KEY (ID)
);

CREATE TABLE RECEIPT_SP_ASSOC (
	ID INTEGER AUTO_INCREMENT,
	CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
	SP_NAME VARCHAR(255) NOT NULL,
	SP_TENANT_DOMAIN VARCHAR(255) DEFAULT 'carbon.super',
	UNIQUE KEY (CONSENT_RECEIPT_ID,SP_NAME,SP_TENANT_DOMAIN),
	PRIMARY KEY (ID)
);

CREATE TABLE SP_PURPOSE_ASSOC (
	ID INTEGER AUTO_INCREMENT,
	RECEIPT_SP_ASSOC INTEGER NOT NULL,
	PURPOSE_ID INTEGER NOT NULL,
	CONSENT_TYPE VARCHAR(255) NOT NULL,
	IS_PRIMARY_PURPOSE INTEGER NOT NULL,
	TERMINATION VARCHAR(255) NOT NULL,
	TERMINATION_DISCLOSURE VARCHAR(1023) NOT NULL,
	THIRD_PARTY_NAME VARCHAR(255) NOT NULL,
	UNIQUE KEY (RECEIPT_SP_ASSOC,PURPOSE_ID),
	PRIMARY KEY (ID)
);

CREATE TABLE SP_PURPOSE_PURPOSE_CAT_ASSOC (
	SP_PURPOSE_ASSOC_ID INTEGER NOT NULL,
	PURPOSE_CATEGORY_ID INTEGER NOT NULL,
	UNIQUE KEY (SP_PURPOSE_ASSOC_ID,PURPOSE_CATEGORY_ID)
);

CREATE TABLE SP_PURPOSE_PII_CATEGORY_ASSOC (
	SP_PURPOSE_ASSOC_ID INTEGER NOT NULL,
	PII_CATEGORY_ID INTEGER NOT NULL,
	UNIQUE KEY (SP_PURPOSE_ASSOC_ID,PII_CATEGORY_ID)
);

CREATE TABLE CONSENT_RECEIPT_PROPERTY (
	CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
	NAME VARCHAR(1023) NOT NULL,
	VALUE VARCHAR(1023) NOT NULL,
	UNIQUE KEY (CONSENT_RECEIPT_ID,NAME)
);

CREATE TABLE RECEIPT_SENSITIVE_CATEGORY (
	CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
	PII_CATEGORY_ID INTEGER NOT NULL,
	UNIQUE KEY (CONSENT_RECEIPT_ID,PII_CATEGORY_ID)
);

ALTER TABLE RECEIPT_SP_ASSOC ADD CONSTRAINT RECEIPT_SP_ASSOC_fk0 FOREIGN KEY (CONSENT_RECEIPT_ID) REFERENCES RECEIPT(CONSENT_RECEIPT_ID);

ALTER TABLE SP_PURPOSE_ASSOC ADD CONSTRAINT SP_PURPOSE_ASSOC_fk0 FOREIGN KEY (RECEIPT_SP_ASSOC) REFERENCES RECEIPT_SP_ASSOC(ID);

ALTER TABLE SP_PURPOSE_ASSOC ADD CONSTRAINT SP_PURPOSE_ASSOC_fk1 FOREIGN KEY (PURPOSE_ID) REFERENCES PURPOSE(ID);

ALTER TABLE SP_PURPOSE_PURPOSE_CAT_ASSOC ADD CONSTRAINT SP_PURPOSE_PURPOSE_CAT_ASSOC_fk0 FOREIGN KEY (SP_PURPOSE_ASSOC_ID) REFERENCES SP_PURPOSE_ASSOC(ID);

ALTER TABLE SP_PURPOSE_PURPOSE_CAT_ASSOC ADD CONSTRAINT SP_PURPOSE_PURPOSE_CAT_ASSOC_fk1 FOREIGN KEY (PURPOSE_CATEGORY_ID) REFERENCES PURPOSE_CATEGORY(ID);

ALTER TABLE SP_PURPOSE_PII_CATEGORY_ASSOC ADD CONSTRAINT SP_PURPOSE_PII_CATEGORY_ASSOC_fk0 FOREIGN KEY (SP_PURPOSE_ASSOC_ID) REFERENCES SP_PURPOSE_ASSOC(ID);

ALTER TABLE SP_PURPOSE_PII_CATEGORY_ASSOC ADD CONSTRAINT SP_PURPOSE_PII_CATEGORY_ASSOC_fk1 FOREIGN KEY (PII_CATEGORY_ID) REFERENCES PII_CATEGORY(ID);

ALTER TABLE CONSENT_RECEIPT_PROPERTY ADD CONSTRAINT CONSENT_RECEIPT_PROPERTY_fk0 FOREIGN KEY (CONSENT_RECEIPT_ID) REFERENCES RECEIPT(CONSENT_RECEIPT_ID);

ALTER TABLE RECEIPT_SENSITIVE_CATEGORY ADD CONSTRAINT RECEIPT_SENSITIVE_CATEGORY_fk0 FOREIGN KEY (CONSENT_RECEIPT_ID) REFERENCES RECEIPT(CONSENT_RECEIPT_ID);

ALTER TABLE RECEIPT_SENSITIVE_CATEGORY ADD CONSTRAINT RECEIPT_SENSITIVE_CATEGORY_fk1 FOREIGN KEY (PII_CATEGORY_ID) REFERENCES PII_CATEGORY(ID);

