CREATE SEQUENCE IF NOT EXISTS CM_PII_CATEGORY_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_PII_CATEGORY (
  ID           INTEGER DEFAULT NEXTVAL('CM_PII_CATEGORY_PK_SEQ'),
  NAME         VARCHAR(255) NOT NULL,
  DESCRIPTION  VARCHAR(1023),
  DISPLAY_NAME VARCHAR(255),
  IS_SENSITIVE INTEGER      NOT NULL,
  TENANT_ID    INTEGER DEFAULT '-1234',
  UUID CHAR(36),
  CONSTRAINT CM_PII_CATEGORY_CNT UNIQUE (NAME, TENANT_ID),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CM_RECEIPT (
  CONSENT_RECEIPT_ID  VARCHAR(255) NOT NULL,
  VERSION             VARCHAR(255) NOT NULL,
  JURISDICTION        VARCHAR(255) NOT NULL,
  CONSENT_TIMESTAMP   TIMESTAMP    NOT NULL,
  COLLECTION_METHOD   VARCHAR(255) NOT NULL,
  LANGUAGE            VARCHAR(255) NOT NULL,
  PII_PRINCIPAL_ID    VARCHAR(255) NOT NULL,
  PRINCIPAL_TENANT_ID INTEGER DEFAULT '-1234',
  POLICY_URL          VARCHAR(255) NOT NULL,
  STATE               VARCHAR(255) NOT NULL,
  PII_CONTROLLER      VARCHAR(2048) NOT NULL,
  VALIDITY_TIME       BIGINT NULL,
  PRIMARY KEY (CONSENT_RECEIPT_ID)
);

CREATE TABLE IF NOT EXISTS CM_CONSENT_AUTHORIZATION (
  CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
  USER_ID            VARCHAR(255) NOT NULL,
  STATUS             VARCHAR(50)  NOT NULL,
  UPDATED_TIME       BIGINT       NOT NULL,
  PRIMARY KEY (CONSENT_RECEIPT_ID, USER_ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_PURPOSE_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_PURPOSE (
  ID            INTEGER DEFAULT NEXTVAL('CM_PURPOSE_PK_SEQ'),
  NAME          VARCHAR(255) NOT NULL,
  DESCRIPTION   VARCHAR(1023),
  PURPOSE_GROUP VARCHAR(255) NOT NULL,
  GROUP_TYPE    VARCHAR(255) NOT NULL,
  TENANT_ID     INTEGER DEFAULT '-1234',
  UUID CHAR(36),
  LATEST_VERSION_ID CHAR(36),
  CONSTRAINT CM_PURPOSE_CNT UNIQUE  (NAME, TENANT_ID, PURPOSE_GROUP, GROUP_TYPE),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_PURPOSE_CATEGORY_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_PURPOSE_CATEGORY (
  ID          INTEGER DEFAULT NEXTVAL('CM_PURPOSE_CATEGORY_PK_SEQ'),
  NAME        VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(1023),
  TENANT_ID   INTEGER DEFAULT '-1234',
  CONSTRAINT CM_PURPOSE_CATEGORY_CNT UNIQUE  (NAME, TENANT_ID),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_RECEIPT_SP_ASSOC_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_RECEIPT_SP_ASSOC (
  ID                 INTEGER DEFAULT NEXTVAL('CM_RECEIPT_SP_ASSOC_PK_SEQ'),
  CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
  SP_NAME            VARCHAR(255) NOT NULL,
  SP_DISPLAY_NAME    VARCHAR(255),
  SP_DESCRIPTION     VARCHAR(1024),
  SP_TENANT_ID       INTEGER DEFAULT '-1234',
  CONSTRAINT CM_RECEIPT_SP_ASSOC_CNT UNIQUE  (CONSENT_RECEIPT_ID, SP_NAME, SP_TENANT_ID),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_SP_PURPOSE_ASSOC_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_SP_PURPOSE_ASSOC (
  ID                     INTEGER DEFAULT NEXTVAL('CM_SP_PURPOSE_ASSOC_PK_SEQ'),
  RECEIPT_SP_ASSOC       INTEGER      NOT NULL,
  PURPOSE_ID             INTEGER      NOT NULL,
  CONSENT_TYPE           VARCHAR(255) NOT NULL,
  IS_PRIMARY_PURPOSE     INTEGER      NOT NULL,
  TERMINATION            VARCHAR(255) NOT NULL,
  THIRD_PARTY_DISCLOSURE INTEGER      NOT NULL,
  THIRD_PARTY_NAME       VARCHAR(255),
  PURPOSE_VERSION_ID     CHAR(36),
  CONSTRAINT CM_SP_PURPOSE_ASSOC_CNT UNIQUE  (RECEIPT_SP_ASSOC, PURPOSE_ID),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_SP_PURPOSE_PURPOSE_CAT_ASSC_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_SP_PURPOSE_PURPOSE_CAT_ASSC (
  ID                  INTEGER DEFAULT NEXTVAL('CM_SP_PURPOSE_PURPOSE_CAT_ASSC_PK_SEQ'),
  SP_PURPOSE_ASSOC_ID INTEGER NOT NULL,
  PURPOSE_CATEGORY_ID INTEGER NOT NULL,
  CONSTRAINT CM_SP_PURPOSE_PURPOSE_CAT_ASSC_CNT UNIQUE  (SP_PURPOSE_ASSOC_ID, PURPOSE_CATEGORY_ID),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_PURPOSE_PII_CAT_ASSOC_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_PURPOSE_PII_CAT_ASSOC (
  ID                 INTEGER DEFAULT NEXTVAL('CM_PURPOSE_PII_CAT_ASSOC_PK_SEQ'),
  PURPOSE_ID         INTEGER NOT NULL,
  CM_PII_CATEGORY_ID INTEGER NOT NULL,
  IS_MANDATORY       INTEGER NOT NULL,
  CONSTRAINT CM_PURPOSE_PII_CAT_ASSOC_CNT UNIQUE  (PURPOSE_ID, CM_PII_CATEGORY_ID),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_SP_PURPOSE_PII_CAT_ASSOC_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_SP_PURPOSE_PII_CAT_ASSOC (
  ID                  INTEGER DEFAULT NEXTVAL('CM_SP_PURPOSE_PII_CAT_ASSOC_PK_SEQ'),
  SP_PURPOSE_ASSOC_ID INTEGER NOT NULL,
  PII_CATEGORY_ID     INTEGER NOT NULL,
  VALIDITY            VARCHAR(1023),
  IS_CONSENTED BOOLEAN DEFAULT TRUE,
  CONSTRAINT CM_SP_PURPOSE_PII_CAT_ASSOC_CNT UNIQUE  (SP_PURPOSE_ASSOC_ID, PII_CATEGORY_ID),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_CONSENT_RECEIPT_PROPERTY_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_CONSENT_RECEIPT_PROPERTY (
  ID                 INTEGER DEFAULT NEXTVAL('CM_CONSENT_RECEIPT_PROPERTY_PK_SEQ'),
  CONSENT_RECEIPT_ID VARCHAR(255)  NOT NULL,
  NAME               VARCHAR(255)  NOT NULL,
  VALUE              VARCHAR(1023) NOT NULL,
  CONSTRAINT CM_CONSENT_RECEIPT_PROPERTY_CNT UNIQUE  (CONSENT_RECEIPT_ID, NAME),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CM_PURPOSE_VERSION (
  UUID CHAR(36) NOT NULL,
  PURPOSE_ID  INTEGER NOT NULL,
  VERSION     VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(1023),
  TENANT_ID   INTEGER DEFAULT '-1234',
  UNIQUE (PURPOSE_ID, VERSION),
  UNIQUE (UUID),
  UNIQUE (PURPOSE_ID, UUID),
  PRIMARY KEY (UUID)
);

CREATE TABLE IF NOT EXISTS CM_PURPOSE_VERSION_PII_CAT_ASSOC (
  PURPOSE_VERSION_ID CHAR(36) NOT NULL,
  CM_PII_CATEGORY_ID INTEGER NOT NULL,
  IS_MANDATORY       INTEGER NOT NULL,
  PRIMARY KEY (PURPOSE_VERSION_ID, CM_PII_CATEGORY_ID)
);

CREATE TABLE IF NOT EXISTS CM_PURPOSE_VERSION_PROPERTY (
  VERSION_ID     CHAR(36)      NOT NULL,
  PROPERTY_KEY   VARCHAR(255)  NOT NULL,
  PROPERTY_VALUE VARCHAR(1023) NOT NULL,
  TENANT_ID      INTEGER       NOT NULL DEFAULT -1234,
  PRIMARY KEY (VERSION_ID, PROPERTY_KEY)
);

ALTER TABLE CM_RECEIPT_SP_ASSOC
  ADD CONSTRAINT CM_RECEIPT_SP_ASSOC_fk0 FOREIGN KEY (CONSENT_RECEIPT_ID) REFERENCES CM_RECEIPT (CONSENT_RECEIPT_ID);

ALTER TABLE CM_SP_PURPOSE_ASSOC
  ADD CONSTRAINT CM_SP_PURPOSE_ASSOC_fk0 FOREIGN KEY (RECEIPT_SP_ASSOC) REFERENCES CM_RECEIPT_SP_ASSOC (ID);

ALTER TABLE CM_SP_PURPOSE_ASSOC
  ADD CONSTRAINT CM_SP_PURPOSE_ASSOC_fk1 FOREIGN KEY (PURPOSE_ID) REFERENCES CM_PURPOSE (ID);

ALTER TABLE CM_SP_PURPOSE_PURPOSE_CAT_ASSC
  ADD CONSTRAINT CM_SP_P_P_CAT_ASSOC_fk0 FOREIGN KEY (SP_PURPOSE_ASSOC_ID) REFERENCES CM_SP_PURPOSE_ASSOC (ID);

ALTER TABLE CM_SP_PURPOSE_PURPOSE_CAT_ASSC
  ADD CONSTRAINT CM_SP_P_P_CAT_ASSOC_fk1 FOREIGN KEY (PURPOSE_CATEGORY_ID) REFERENCES CM_PURPOSE_CATEGORY (ID);

ALTER TABLE CM_SP_PURPOSE_PII_CAT_ASSOC
  ADD CONSTRAINT CM_SP_P_PII_CAT_ASSOC_fk0 FOREIGN KEY (SP_PURPOSE_ASSOC_ID) REFERENCES CM_SP_PURPOSE_ASSOC (ID);

ALTER TABLE CM_SP_PURPOSE_PII_CAT_ASSOC
  ADD CONSTRAINT CM_SP_P_PII_CAT_ASSOC_fk1 FOREIGN KEY (PII_CATEGORY_ID) REFERENCES CM_PII_CATEGORY (ID);

ALTER TABLE CM_CONSENT_RECEIPT_PROPERTY
  ADD CONSTRAINT CM_CONSENT_RECEIPT_PRT_fk0 FOREIGN KEY (CONSENT_RECEIPT_ID) REFERENCES CM_RECEIPT (CONSENT_RECEIPT_ID);

ALTER TABLE CM_CONSENT_AUTHORIZATION
  ADD CONSTRAINT CM_CONSENT_AUTH_fk0 FOREIGN KEY (CONSENT_RECEIPT_ID) REFERENCES CM_RECEIPT (CONSENT_RECEIPT_ID);

ALTER TABLE CM_SP_PURPOSE_ASSOC
  ADD CONSTRAINT CM_SP_PURPOSE_ASSOC_fk2 FOREIGN KEY (PURPOSE_ID, PURPOSE_VERSION_ID) REFERENCES CM_PURPOSE_VERSION (PURPOSE_ID, UUID);

ALTER TABLE CM_PURPOSE_VERSION
  ADD CONSTRAINT CM_PURPOSE_VERSION_fk0 FOREIGN KEY (PURPOSE_ID) REFERENCES CM_PURPOSE (ID);

ALTER TABLE CM_PURPOSE
  ADD CONSTRAINT CM_PURPOSE_LATEST_VER_fk FOREIGN KEY (ID, LATEST_VERSION_ID) REFERENCES CM_PURPOSE_VERSION (PURPOSE_ID, UUID);

ALTER TABLE CM_PURPOSE_VERSION_PII_CAT_ASSOC
  ADD CONSTRAINT CM_PV_PII_CAT_ASSOC_fk0 FOREIGN KEY (PURPOSE_VERSION_ID) REFERENCES CM_PURPOSE_VERSION (UUID) ON DELETE CASCADE;

ALTER TABLE CM_PURPOSE_VERSION_PII_CAT_ASSOC
  ADD CONSTRAINT CM_PV_PII_CAT_ASSOC_fk1 FOREIGN KEY (CM_PII_CATEGORY_ID) REFERENCES CM_PII_CATEGORY (ID);

ALTER TABLE CM_PURPOSE_VERSION_PROPERTY
  ADD CONSTRAINT CM_PV_PROPERTY_fk0 FOREIGN KEY (VERSION_ID) REFERENCES CM_PURPOSE_VERSION (UUID) ON DELETE CASCADE;

-- Add indexes for nullable UUID columns
CREATE INDEX IF NOT EXISTS CM_PII_CATEGORY_UUID_IDX ON CM_PII_CATEGORY (UUID);
CREATE INDEX IF NOT EXISTS CM_PURPOSE_UUID_IDX ON CM_PURPOSE (UUID);

INSERT INTO CM_PURPOSE (NAME, DESCRIPTION, PURPOSE_GROUP, GROUP_TYPE, TENANT_ID) VALUES ('DEFAULT', 'For core functionalities of the product', 'DEFAULT', 'SP', '-1234');

INSERT INTO CM_PURPOSE_CATEGORY (NAME, DESCRIPTION, TENANT_ID) VALUES ('DEFAULT','For core functionalities of the product', '-1234');
